# Generated by Django 6.0.1 on 2026-02-07 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('Alert', 'Alert'), ('Info', 'Info'), ('Reminder', 'Reminder')], max_length=20)),
                ('status', models.CharField(choices=[('Read', 'Read'), ('Unread', 'Unread')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myparking.user')),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(max_length=10)),
                ('slot_type', models.CharField(choices=[('Regular', 'Regular'), ('EV', 'EV'), ('Handicap', 'Handicap')], max_length=20)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Reserved', 'Reserved'), ('Occupied', 'Occupied')], max_length=20)),
                ('price_per_hour', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('parking_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myparking.parkinglot')),
            ],
            options={
                'db_table': 'parking_slot',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('booking_status', models.CharField(choices=[('Reserved', 'Reserved'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], max_length=20)),
                ('booking_code', models.CharField(max_length=50, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myparking.user')),
                ('parking_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myparking.parkingslot')),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('Card', 'Card'), ('Wallet', 'Wallet'), ('Cash', 'Cash')], max_length=20)),
                ('payment_status', models.CharField(choices=[('Success', 'Success'), ('Pending', 'Pending'), ('Failed', 'Failed')], max_length=20)),
                ('transaction_id', models.CharField(max_length=100)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Myparking.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Myparking.user')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
