# Generated by Django 6.0.1 on 2026-02-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentdiv',
            field=models.IntegerField(null=True),
        ),
    ]
