# Generated by Django 6.0.1 on 2026-02-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pcolor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pstatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentcity',
            field=models.CharField(max_length=100),
        ),
    ]
