# Generated by Django 6.0.1 on 2026-02-07 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_product_pcolor_product_pstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studenthobbies', models.CharField(choices=[('reading', 'Reading'), ('writing', 'Writing'), ('traveling', 'Traveling'), ('music', 'Music')], max_length=100)),
                ('studentmarks', models.IntegerField()),
                ('studentgrade', models.CharField(max_length=100)),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
